version: "2"

run:
  timeout: 10m
  tests: false

output:
  show-stats: true
  sort-order:
    - file
    - severity
    - linter

linters:
  enable:
    - asciicheck
    - bidichk
    - containedctx
    - contextcheck
    - copyloopvar
    - durationcheck
    - embeddedstructfieldcheck
    - errcheck
    - errchkjson
    - exhaustive
    - forcetypeassert
    - gocheckcompilerdirectives
    - gochecksumtype
    - gosec
    - govet
    - iface
    - ineffassign
    - modernize
    - nilerr
    - noctx
    - nolintlint
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - sloglint
    - staticcheck
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
        - fmt.Print
        - fmt.Printf
        - fmt.Println
    exhaustive:
      default-signifies-exhaustive: true
    staticcheck:
      checks:
        - "all"
        - "-QF*"
        - "-ST*"
    gocritic:
      disabled-checks:
        - ifElseChain
    unused:
      exported-fields-are-used: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
